config/routes.rb
HeadfirstMebay::Application.routes.draw do

  
  
  resources :ads
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :description, :email, :img_url, :name, :price, :seller_id
  validates_presence_of :price
  validates_presence_of :name
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  http_basic_authenticate_with :name => "sergio", :password => "123", :only => [:edit, :update, :destroy]
  
  def index
    @ads = Ad.all
  end
  
  def show
    @ad = Ad.find(params[:id])
  end
  
  def new
    @ad = Ad.new
  end
  
  def create
    @ad = Ad.new(params[:ad])
    
    if @ad.save
      redirect_to @ad, notice: "Ad was successfully created."
    else
      render action: 'new'
    end
  end
  
  def edit
    @ad = Ad.find(params[:id])    
  end
  
  def update
    @ad = Ad.find(params[:id])
    @ad.update_attributes(params[:ad])
    redirect_to @ad, notice: "Ad was successfully updated"
  end
  
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    
    redirect_to ads_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for @ad do |f| %>
<% if @ad.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

    <ul>
    <% @ad.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :price %><br />
  <%= f.text_field :price %>
</p>
<p>
  <%= f.label :seller_id %><br />
  <%= f.text_field :seller_id %>
</p>
<p>
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :img_url %><br />
  <%= f.text_field :img_url %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ad_path %>

app/views/ads/index.html.erb
<h1>All Ads</h1>
<% @ads.each do |ad| %>
  <ul>
		<li>			
			<%= link_to ad.name, ad %>
			<%= link_to "Delete", ad, confirm: "Are you sure?", method: :delete %>
		</li>
	</ul>
<% end %>

<br/>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New Add</h1>
<%= render :partial => 'form' %>
<%= link_to "Back", ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Name:</b><%= @ad.name %>
</p>
<p>
	<b>Description:</b><%= @ad.description %>
</p>
<p>
	<b>Price:</b><%= @ad.price %>
</p>
<p>
	<b>Seller Id:</b><%= @ad.seller_id %>
</p>
<p>
	<b>Email:</b><%= @ad.email %>
</p>
<p>
	<img src="<%= @ad.img_url %>">
</p>

<br/>

<%= link_to 'Edit Ad', edit_ad_path(@ad) %> |
<%= link_to 'Back to Ads', ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
	<head>
		<title>
			Ads: <%= controller.action_name %>
		</title><%= stylesheet_link_tag    "/stylesheets/default.css" %><%= javascript_include_tag "application" %><%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<div>
					<h1>
						MeBay
					</h1>
					<ul>
						<li>
							<a href="/ads/">All Ads</a>
						</li>
					</ul>
				</div>
			</div>
			<div id="content">
				<%= yield %>
			</div>
			<div id="clearfooter"></div>
		</div>
		<div id="footer"></div>
	</body>
</html>